// Generated by https://quicktype.io

export interface DetailListResponse {
    created_by:     string;
    description:    string;
    favorite_count: number;
    id:             number;
    iso_639_1:      string;
    item_count:     number;
    items:          any[];
    name:           string;
    page:           number;
    poster_path:    null;
    total_pages:    number;
    total_results:  number;
}
